{
 "title": "ANP",
 "time": { "from": "2021-01-03T00:00:00.000Z", "to": "2022-04-25T00:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "Produto",
    "query": "select distinct(\"Produto\") from anp"
   },
   {
    "name": "Bandeira",
    "query": "select distinct(\"Bandeira\") from anp"
   }
  ]
 },
 "panels": [
  {
   "title": "Total de postos por bandeira - Série histórica",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select date_trunc('year', \"Data da Coleta\") as \"time\", \n       count(distinct(\"CNPJ da Revenda\")) as \"Quantidade de postos\", \n       \"Bandeira\" \nfrom anp \nwhere \"Bandeira\" in ($Bandeira) \nGROUP BY \"Bandeira\", date_trunc('year', \"Data da Coleta\")\norder by \"time\""
    }
   ]
  },
  {
   "title": "Total de postos por estado",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select \"Estado - Sigla\", count(\"CNPJ da Revenda\") FROM gas_stations GROUP BY \"Estado - Sigla\""
    }
   ]
  },
  {
   "title": "Total de postos por bandeira",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct(\"CNPJ da Revenda\")), \"Bandeira\" from gas_stations where \"Bandeira\" in ($Bandeira) GROUP BY \"Bandeira\""
    }
   ]
  },
  {
   "title": "Distribuição de postos por estado e bandeira",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "select \"Estado - Sigla\",  \n      count(distinct(CASE WHEN \"Bandeira\" = 'RAIZEN' THEN \"CNPJ da Revenda\" END)) as \"Quantidade de postos - RAIZEN\",\n      count(distinct(CASE WHEN \"Bandeira\" = 'BRANCA' THEN \"CNPJ da Revenda\" END)) as \"Quantidade de postos - B. BRANCA\",\n      count(distinct(CASE WHEN \"Bandeira\" = 'VIBRA' THEN \"CNPJ da Revenda\" END)) as \"Quantidade de postos - VIBRA\"\nFROM gas_stations \nGROUP BY \"Estado - Sigla\""
    }
   ]
  },
  {
   "title": "Último preço médio disponível",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select date_trunc('week', \"Data da Coleta\") as \"time\",\n      avg(\"Valor de Venda\") as \"Preço médio semanal\",\n      \"Produto\"\nfrom anp\nwhere \"Produto\" in ($Produto)\ngroup by date_trunc('week', \"Data da Coleta\"), \"Produto\"\norder by \"time\""
    }
   ]
  },
  {
   "title": "Preço médio Brasil",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "rawSql": "select date_trunc('week', \"Data da Coleta\") as \"time\",\n      avg(\"Valor de Venda\") as \"Preço médio semanal\",\n      \"Produto\"\nfrom anp\nwhere \"Produto\" in ($Produto)\ngroup by date_trunc('week', \"Data da Coleta\"), \"Produto\"\norder by \"time\""
    }
   ]
  }
 ]
}